services:
  db:
    image: mysql:latest
    container_name: ledgar-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ledgar_db

    ports:
      - "3306:3306" # Open port for Development
    volumes:
      - ledgar-db-data:/var/lib/mysql

volumes:
  ledgar-db-data:
    driver: local