services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ledgar_db
    ports:
      - "3306:3306"
    volumes:
      - ledgar-db-data:/var/lib/mysql

  backend:
    container_name: ledgar-backend
    build:
      context: .
    # env_file:
    #   - .env
    environment:
      DATABASE_URL: mysql://root:root@db:3306/ledgar_db
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  ledgar-db-data:
    driver: local
